[package]
name = 'unen_net'
version.workspace = true
edition.workspace = true

# Error Handling
[dependencies.thiserror]
workspace = true

# Algorithm
[dependencies.bincode]
workspace = true
[dependencies.crc32fast]
workspace = true
