name: CI 🛠️

on:
  push:
    branches: ['main']
  pull_request:
    type: [opened, synchronize]
  merge_group:
    type: [checks_requested]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Build
        run: cargo build

      - name: Check format
        run: cargo fmt --check

      - name: Ask clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test
